"""CLI entry point: python -m lab <command>."""
from __future__ import annotations

import argparse
import sys

from .config import load_lab_config
from .report import print_leaderboard
from .runner import run_lab
from .storage import LabStore


# --- commands ---

def cmd_run(args: argparse.Namespace) -> int:
    cfg = load_lab_config(args.config)
    print(f"loading data ({cfg.data.source}) ...")

    run = run_lab(cfg, parallel=not args.sequential)
    print_leaderboard(run)

    if args.no_save:
        return 0

    if args.no_charts:
        import lab.charts as charts
        charts.HAVE_MPL = False

    store = LabStore(cfg.output.dir)
    run_dir = store.save(run, write_html=not args.no_html)
    print(f"\n  saved  -> {run_dir}")

    report = run_dir / "report.html"
    if report.exists():
        print(f"  report -> {report}")
    return 0


def cmd_list(args: argparse.Namespace) -> int:
    store = LabStore(args.dir)
    runs = store.list_runs()
    if not runs:
        print("no saved runs")
        return 0

    for r in runs:
        try:
            s = store.load_summary(r)
            best = max(
                s["strategies"],
                key=lambda x: x["metrics"].get("total_return_pct", 0.0),
            )
            print(
                f"  {r.name}  {s['name']:<24}  "
                f"best={best['name']:<14}  "
                f"return={best['metrics'].get('total_return_pct', 0):+.2f}%"
            )
        except Exception as e:
            print(f"  {r.name}  <unreadable: {e}>")
    return 0


def cmd_charts(args: argparse.Namespace) -> int:
    """
    Chart utilities for saved runs.

    Charts can only be regenerated by re-running the lab, because they need
    the in-memory equity curves and fills. This command just shows the owner
    what's available and how to regenerate.
    """
    store = LabStore(args.dir)
    runs = store.list_runs()
    if not runs:
        print("no saved runs")
        return 1

    if args.latest:
        target = runs[-1]
    elif args.run_id:
        target = next((r for r in runs if r.name == args.run_id), None)
        if target is None:
            print(f"run not found: {args.run_id}")
            return 1
    else:
        # no selector: list all runs that have charts
        print(f"runs in {args.dir}:")
        for r in runs:
            try:
                s = store.load_summary(r)
                charts = s.get("charts", [])
                marker = "charts" if charts else "no charts"
                print(f"  {r.name}  [{marker}]")
            except Exception as e:
                print(f"  {r.name}  <unreadable: {e}>")
        print("\ntip: pass --latest or --run-id <name> to inspect one run")
        return 0

    summary = store.load_summary(target)
    charts = summary.get("charts", [])

    print(f"run: {target.name}")
    print(f"  name  : {summary.get('name')}")
    print(f"  saved : {summary.get('saved_at')}")

    if charts:
        print(f"  charts ({len(charts)}):")
        for name in charts:
            print(f"    {target / name}")
    else:
        print("  charts: none")

    print("\nnote: charts are generated during 'lab run'.")
    print("      to regenerate, re-run with the same config:")
    print(f"      python -m lab run --config <yaml>")
    return 0

def cmd_report(args: argparse.Namespace) -> int:
    """Print the path to a saved run's HTML report."""
    store = LabStore(args.dir)
    runs = store.list_runs()
    if not runs:
        print("no saved runs")
        return 1

    if args.latest:
        target = runs[-1]
    else:
        target = next((r for r in runs if r.name == args.run_id), None)
        if target is None:
            print(f"run not found: {args.run_id}")
            return 1

    report = target / "report.html"
    if not report.exists():
        print(f"no report for {target.name}")
        print("(re-run without --no-html to generate one)")
        return 1
    print(report)
    return 0

# --- entry point ---

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="lab",
        description="Virtual trading lab: run multi-strategy experiments",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    # run
    p_run = sub.add_parser("run", help="run a lab experiment")
    p_run.add_argument("--config", required=True, help="path to a lab YAML")
    p_run.add_argument("--sequential", action="store_true",
                       help="disable parallel execution")
    p_run.add_argument("--no-save", action="store_true",
                       help="do not write results to disk")
    p_run.add_argument("--no-charts", action="store_true",
                       help="skip chart generation")
    p_run.set_defaults(func=cmd_run)

    # list
    p_list = sub.add_parser("list", help="list saved lab runs")
    p_list.add_argument("--dir", default="data/lab_runs")
    p_list.set_defaults(func=cmd_list)

    # charts
    p_charts = sub.add_parser("charts", help="inspect charts for saved runs")
    p_charts.add_argument("--dir", default="data/lab_runs")
    p_charts.add_argument("--latest", action="store_true",
                          help="use the most recent run")
    p_charts.add_argument("--run-id", default="",
                          help="specific run directory name")
    p_charts.set_defaults(func=cmd_charts)

    p_run.add_argument("--no-html", action="store_true",
                       help="skip HTML report generation")

    p_report = sub.add_parser("report", help="print path to a saved run's HTML report")
    p_report.add_argument("--dir", default="data/lab_runs")
    p_report.add_argument("--latest", action="store_true")
    p_report.add_argument("--run-id", default="")
    p_report.set_defaults(func=cmd_report)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())